#!name=喜马拉雅会员

#!desc=x

#!homepage=@x

#!author=x

#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/xmlyad.png

[URL Rewrite]
^http[s]?:\/\/openapi\.mysteel\.com/v5/getAdv.htm - reject
^http[s]?.+ulogs.umeng.com - reject
^http[s]?.+gslbali.ximalaya.com - reject
^http[s]?.+adse.ximalaya.com - reject
^http[s]?.+gslbtx.ximalaya.com - reject
^http[s]?.+location.ximalaya.com - reject
^http[s]?.+passport.ximalaya.com - reject
^http[s]?.+adbehavior.ximalaya.com - reject
^http[s]?.+ad.ximalaya.com - reject
^http[s]?.+audid-api.taobao.com - reject
^http[s]?:\/\/((.+ximalaya.+)|(.+xmcdn.+))\/mobile-playpage\/track\/v3\/baseInfo\/ts https://raw.githubusercontent.com/kleinmoretti-xu/QuantumultXScript/main/script/xmly/ximalayatk.js? header

[Script]

喜马拉雅 = type=http-response,pattern=^http[s]?:\/\/((.+ximalaya.+)|(.+xmcdn.+)).*\/(playpage\/tabs\/v2|v1\/album\/track\/ts|v1\/album\/price|v2\/homePage|business-vip-presale-mobile-web\/page\/ts|vip\/v1\/recommand|track\/v3\/baseInfo|v1\/module\/data\/dynamic|basicInfo\/dynamic\/ts).*$,requires-body=1,script-path=https://raw.githubusercontent.com/kleinmoretti-xu/QuantumultXScript/main/script/xmly/xmly.js

[MITM]

hostname = *xima*,*xmcdn*,*.ximalaya.com,*.xmcdn.com

